[package]
name = "Rusty-6502"
version = "0.0.1"
edition = "2024"
authors = ["townlake101@gmail.com"]
description = "A 6502 emulated using Rust"
license = "MIT"


repository = "https://github.com/Shane-Wood-TL/Rusty-6502/"

[dependencies]
